move linux bitmanip and newlib rv64gc to self hosted runners
ewlu/gcc-precommit-ci pull request #1620
Opened 2024-05-28 21:00 UTC by ewlu

2024-06-17 20:45 UTC, patrick-rivos commented
```
6  SelfHosted - 2 runners 3 hrs per patch 
20 GitHub     - 2 runners 6 hr per patch
```
Delta before/after this patch:
Throughput is 1 patch /hr -> 3/4 patch /hr
Latency 6 hr -> 3 hr

2024-06-25 17:30 UTC, patrick-rivos requested changes

2024-06-25 17:30 UTC, patrick-rivos commented on .github/workflows/run-checks.yaml
> +  #   secrets: inherit
Can you add the singlelib build-only target so we have something to compare warnings against for precommit?

2024-06-25 17:33 UTC, ewlu commented on .github/workflows/run-checks.yaml
> +  #   secrets: inherit
It's been added here https://github.com/ewlu/gcc-precommit-ci/pull/1620/files/4a7454aa475d540eaafd9fc598ddec5f2c7e4d14#diff-19d039d380ffa5e876af61bf876245164c5e0a96f684df998f7e0c98e746270fR479

2024-06-27 18:04 UTC, patrick-rivos commented on .github/workflows/run-checks.yaml
> -            rv32imc_zba_zbb_zbc_zbs-ilp32d, # rv32 bitmanip uc target
Any configure scripts that are no longer referenced anywhere should be deleted

2024-06-27 18:05 UTC, patrick-rivos commented on configure-scripts/rv64gc_zba_zbb_zbc_zbs-lp64d
> +# Used for self-hosted bitmanip targets
Mention that it's linux-only

2024-06-27 18:10 UTC, patrick-rivos commented on .github/workflows/test-regression.yaml
> +      # There is only one github target now which is rv32imc_zba_zbb_zbc_zbs-ilp32
Ditto - pulled into multilib

2024-06-27 18:19 UTC, patrick-rivos commented on .github/workflows/test-regression.yaml
> +      # There is only one github target now which is rv32imc_zba_zbb_zbc_zbs-ilp32
Also since we aren't testing on github anymore can we throw an error if we enter the test step?

2024-06-27 18:19 UTC, patrick-rivos commented on .github/workflows/test-regression.yaml
> +      - name: Get target string
This is great - thanks for pulling this out

2024-06-27 18:21 UTC, patrick-rivos commented on .github/workflows/run-checks.yaml
> +  cmreg-bitmanip-sh: # Bitmanip self hosted runner multilib build
I'd prefer `cmreg-linux-sh` since the step is just a wrapper that calls linux on the targets

2024-06-27 18:24 UTC, patrick-rivos commented on .github/actions/download-all-comparison-artifacts/action.yaml
> +    - name: Download linux rv64 bitmanip multilib
Can you move this to the bottom or top so the vector multilib downloads can be adjacent?

2024-06-28 20:34 UTC, patrick-rivos requested changes
Staging run failed to create results:
https://github.com/ewlu/gcc-precommit-ci/issues/1812#issuecomment-2195480744

2024-07-19 22:23 UTC, patrick-rivos approved these changes

2024-07-22 16:44 UTC, merged