Parse new build warnings Integration
ewlu/gcc-precommit-ci pull request #1919
Opened 2024-07-16 21:38 UTC by kevinl-rivosinc

2024-07-19 21:46 UTC, patrick-rivos requested changes

2024-07-19 21:46 UTC, patrick-rivos commented on .github/actions/common/download-build-log-artifact/action.yaml
> +      continue-on-error: true
Add newline to the end of this file

2024-07-19 21:46 UTC, patrick-rivos commented on .github/actions/common/unzip-all-zips/action.yaml
> +        ls ${{ inputs.output-dir }}
Ditto

2024-07-19 21:46 UTC, patrick-rivos commented on .github/actions/download-all-build-log-artifacts/action.yaml
> +name: "Download All Buid Log Artifacts"
```suggestion
name: "Download All Build Log Artifacts"
```

2024-07-19 21:46 UTC, patrick-rivos commented on .github/actions/download-all-build-log-artifacts/action.yaml
> +        build-artifact-name: linux-rv64gcv-lp64d-${{ inputs.gcchash }}-multilib-build-log
rv64gcv is different on pre/postcommit so you'll probably run into issues when comparing. There are likely extra warnings on postcommit which will show up as resolved on every run:
https://github.com/patrick-rivos/gcc-postcommit-ci/blob/main/configure-scripts/rv64gcv-lp64d

2024-07-19 21:46 UTC, patrick-rivos commented on .github/workflows/patchworks.yaml
> +      - uses: actions/checkout@v3
```suggestion
      - uses: actions/checkout@v4
```

2024-07-19 21:46 UTC, patrick-rivos commented on .github/workflows/patchworks.yaml
> +      # Download the current build logs
You can remove these comments, the name describe what's going on

2024-07-19 21:55 UTC, kevinl-rivosinc commented on .github/actions/common/download-build-log-artifact/action.yaml
> +      continue-on-error: true
I feel like I'll miss a lot of eof like this. Do we have a plan for pre-commit possibly?

2024-07-19 22:17 UTC, patrick-rivos commented on .github/actions/common/download-build-log-artifact/action.yaml
> +      continue-on-error: true
If you want to add a linter precommit feel free to - I'd welcome it :-)

2024-07-22 17:09 UTC, kevinl-rivosinc commented on .github/actions/download-all-build-log-artifacts/action.yaml
> +        build-artifact-name: linux-rv64gcv-lp64d-${{ inputs.gcchash }}-multilib-build-log
Ah I see. Then I'll only compare non-multilib for now and later create a support for multilib in the future

2024-07-22 18:08 UTC, kevinl-rivosinc commented on .github/actions/download-all-build-log-artifacts/action.yaml
> +    # TODO: Later support Multilib by isolating targets
I'll leave a new comment `#TODO: Later support Multilib. Restriction: https://github.com/ewlu/gcc-precommit-ci/pull/1919#discussion_r1686874053` for a helpful pointer

2024-07-22 18:11 UTC, patrick-rivos approved these changes

2024-07-29 18:21 UTC, patrick-rivos approved these changes

2024-07-29 18:24 UTC, ewlu approved these changes

2024-07-29 18:45 UTC, merged