keep baseline when building build only targets when running testsuite
ewlu/gcc-precommit-ci pull request #1989
Opened 2024-08-01 21:23 UTC by ewlu

2024-08-01 21:43 UTC, kevinl-rivosinc commented on .github/workflows/run-checks.yaml
> +      build_only: 'run_warnings'
I believe `inputs.build_only != 'true'` was changed to `inputs.build_only == 'false'` for this line. 

How would run_warnings be used in the future? I wasn't able to find a place that uses build_only: 'run_warnings'.

2024-08-01 21:48 UTC, ewlu commented on .github/workflows/run-checks.yaml
> +      build_only: 'run_warnings'
setting `build_only: 'true'` caused a problem where it checked out to `tot_hash` instead of `baseline_hash`. This caused a build error which was reported to patchwork, even though the patch itself had nothing to do with it. Setting `build_only: 'false'` would cause the testsuite to run which we don't want to do. the `run_warnings` can be used to prevent checking out to `tot_hash` (and therefore keeping it on `baseline_hash`) while also giving us another way of modifying the flow for when we add the build warnings. Currently `run_warnings` gives us the affect of `build_only` without running the testsuite

2024-08-01 21:51 UTC, kevinl-rivosinc approved these changes

2024-08-02 05:03 UTC, patrick-rivos requested changes

2024-08-02 05:03 UTC, patrick-rivos commented on .github/actions/extract-apply-patches-trunk-or-baseline/action.yaml
>          working-directory: riscv-gnu-toolchain
What's the behavior when an apply fails for the warning build?
The current setup will have the run_warnings build fail on the apply step when running build-only patches.

2024-08-02 18:10 UTC, ewlu commented on .github/actions/extract-apply-patches-trunk-or-baseline/action.yaml
>          working-directory: riscv-gnu-toolchain
Nice catch. If the patch applies to tip of tree but not the baseline, since `build_only: 'run_warning'` is hardcoded, it would have tried running the single target build-only for warning comparisons against the baseline hash. Will update

2024-08-02 18:49 UTC, patrick-rivos approved these changes
LGTM

2024-08-05 22:32 UTC, merged