refactor to use one issue with issue comments for reporting
ewlu/gcc-precommit-ci pull request #317
Opened 2023-10-18 23:13 UTC by ewlu

2023-10-18 23:54 UTC, patrick-rivos requested changes

2023-10-18 23:54 UTC, patrick-rivos commented on .github/workflows/run_checks.yaml
> +          body-path: comment.md
I believe the path is `riscv-gnu-toolchain/comment.md` since our default run directory is `riscv-gnu-toolchain`

2023-10-18 23:54 UTC, patrick-rivos commented on .github/workflows/lint.yaml
> +          tail -n+4 linter_fail_report.md >> temp_comment.md
This seems fine as long as we follow it up with a lint refactor to not emit those first 4 lines

2023-10-18 23:54 UTC, patrick-rivos commented on .github/workflows/lint.yaml
> +            '## Lint Status'
Are quotes needed here/should they include the second line?

2023-10-18 23:54 UTC, patrick-rivos commented on .github/workflows/lint.yaml
> +          tail -n+4 linter_fail_report.md >> temp_comment.md
Also TODO for me: use gcc directly to lint

2023-10-18 23:54 UTC, patrick-rivos commented on .github/workflows/build-target.yaml
> +          echo "## Testsuite Status" > comment.md
Maybe add pending to the body of this (or something to indicate that it hasn't started/is waiting on builds)?

2023-10-18 23:54 UTC, patrick-rivos commented on .github/workflows/test-regression.yaml
> +          printf "\n[Additional information](https://github.com/ewlu/gcc-precommit-ci/issues/${{ inputs.issue_num }})\n" >> comment.md
Looks like this is the first instance of `comment.md` in this job. We should have a `## Build status/pending` thing (or just include this stuff when we initially make the comment).

2023-10-18 23:54 UTC, patrick-rivos commented on .github/workflows/run_checks.yaml
> +  create-issue:
needs a `runs-on` thingy

2023-10-18 23:54 UTC, patrick-rivos commented on .github/workflows/test-regression.yaml
> +        if: ${{ steps.build-pending.outcome == 'failure' }}
I don't think update-comment has a `outcome` output.
https://github.com/search?q=repo%3Apeter-evans%2Fcreate-or-update-comment+outcome&type=code

2023-10-18 23:54 UTC, patrick-rivos commented on .github/workflows/test-regression.yaml
> +          printf "\n[Additional information](https://github.com/ewlu/gcc-precommit-ci/issues/${{ inputs.issue_num }})\n" >> comment.md
This appends to the existing build comment (not what we want for the testsuite status).
update_issue_status outputs `issue.md`. That might be what you mean to refer to.

2023-10-18 23:54 UTC, patrick-rivos commented on .github/workflows/test-regression.yaml
> +        if: ${{ steps.test-waiting.outcome == 'failure' }}
Same as above - outcome isn't a thing :frowning_face:

2023-10-18 23:54 UTC, patrick-rivos commented on .github/workflows/test-regression.yaml
> +          python scripts/update_issue_status.py -token ${{ secrets.GITHUB_TOKEN }} -state success -comment ${{ inputs.build_comment_id }} -target ${{ inputs.mode }}-${{ inputs.target }}-${{ inputs.mu
update_issue_status outputs `issue.md`. That might be what you mean to refer to with `comment.md` later on.

2023-10-18 23:54 UTC, patrick-rivos commented on .github/workflows/test-regression.yaml
> +          python scripts/update_issue_status.py -token ${{ secrets.GITHUB_TOKEN }} -state 'Build failure. Please check the ${{ steps.build-log.outputs.build_log_name }} artifact' -comment ${{ inputs.
Same deal w/ issue.md

2023-10-18 23:54 UTC, patrick-rivos commented on .github/workflows/test-regression.yaml
> +        if: ${{ always() && steps.build-complete.outcome == 'failure' }}
Same deal w/ outcome

2023-10-18 23:54 UTC, patrick-rivos commented on .github/workflows/test-regression.yaml
> +          python scripts/update_issue_status.py -token ${{ secrets.GITHUB_TOKEN }} -state 'Testsuite was not ran. Patch did not apply to known baseline.' -comment ${{ inputs.test_comment_id }} -targe
Same as above update_issue_status outputs `issue.md`.

2023-10-18 23:54 UTC, patrick-rivos commented on .github/workflows/generate-precommit-summary.yaml
> +          python scripts/update_issue_status.py -token ${{ secrets.GITHUB_TOKEN }} -comment ${{ inputs.build_comment_id }} -repo ewlu/gcc-precommit-ci -failure
Callsite hasn't changed yet

2023-10-18 23:54 UTC, patrick-rivos commented on .github/workflows/test-regression.yaml
> +          comment-filepath: riscv-gnu-toolchain/comment.md
We probably shouldn't do this for build-only runs

2023-10-18 23:54 UTC, patrick-rivos commented on .github/workflows/generate-precommit-summary.yaml
> +          python scripts/update_issue_status.py -token ${{ secrets.GITHUB_TOKEN }} -comment ${{ inputs.build_comment_id }} -repo ewlu/gcc-precommit-ci -failure
We already report failures here: line 214 in test-regression.yaml

2023-10-19 00:00 UTC, ewlu commented on .github/workflows/lint.yaml
> +            '## Lint Status'
I think the quotes are needed otherwise the # is treated as a question mark

2023-10-19 00:01 UTC, ewlu commented on .github/workflows/build-target.yaml
> +          echo "## Testsuite Status" > comment.md
Will get populated early in the matrix with status for each target being 'waiting'

2023-10-19 00:04 UTC, ewlu commented on .github/workflows/test-regression.yaml
> +        if: ${{ steps.test-waiting.outcome == 'failure' }}
https://github.com/ewlu/action_testing/actions/runs/6554589331/job/17801807424

2023-10-19 18:20 UTC, merged