move build completion report to subaction
ewlu/gcc-precommit-ci pull request #515
Opened 2023-10-30 20:48 UTC by ewlu

2023-10-30 22:05 UTC, patrick-rivos requested changes
Overall looks good to me. That's a _lot_ of inputs but keeping these two text-dense step series in sync is a good idea.

2023-10-30 22:05 UTC, patrick-rivos commented on .github/actions/report-build-complete-status/action.yaml
> +          python scripts/post_check_to_patchworks.py -event ${{ github.event_name }} -repo ewlu/gcc-precommit-ci -pid $(tail -n 1 patches/${{ inputs.patch_name }})  -desc 'Build failed' -iid '${{ inp
Use input patchwork_api

2023-10-30 22:05 UTC, patrick-rivos commented on .github/actions/report-build-complete-status/action.yaml
> +          python scripts/post_check_to_patchworks.py -event ${{ github.event_name }} -repo ewlu/gcc-precommit-ci -pid $(tail -n 1 patches/${{ inputs.patch_name }})  -desc 'Build passed' -iid '${{ inp
Ditto

2023-10-30 22:41 UTC, patrick-rivos approved these changes
LGTM - Just a heads up/highlighting that this will cause patchworks build reporting to be on as soon as this is merged.

2023-10-31 14:46 UTC, ewlu commented
It won't be sending build reporting due to https://github.com/ewlu/gcc-precommit-ci/commit/4ae6f86c3e5094bc983878d0b92679fcab2ac3d6 at the start of the refactor branch

2023-11-01 16:34 UTC, merged