add new lenient allowlist and consume sum files
ewlu/gcc-precommit-ci pull request #618
Opened 2023-11-08 01:50 UTC by ewlu

Merge only after we have sum files on postcommit

2023-11-08 18:56 UTC, patrick-rivos requested changes
Bones look good - I'll take a closer look once the misc files get removed.

2023-11-08 18:56 UTC, patrick-rivos commented on test/benchmarks/dhrystone/dhrystone_main.c
> +// See LICENSE for license details.
We can remove this file

2023-11-08 18:56 UTC, patrick-rivos commented on test/benchmarks/dhrystone/dhrystone.h
> +// See LICENSE for license details.
We can remove this file

2023-11-08 18:56 UTC, patrick-rivos commented on test/benchmarks/dhrystone/dhrystone.c
> +// See LICENSE for license details.
We can remove this file

2023-11-08 18:56 UTC, patrick-rivos commented on test/benchmarks/dhrystone/check
> +#!/bin/bash
We can remove this file

2023-11-08 18:56 UTC, patrick-rivos commented on test/allowlist/binutils/glibc.log
> +#
Can remove binutils allowlist

2023-11-13 17:30 UTC, ewlu commented
#658 with new allowlist
#654 with old allowlist

2023-11-13 17:39 UTC, patrick-rivos approved these changes
LGTM! I can send another PR to update the allowlist with the fails I've noticed.

2023-11-13 17:39 UTC, patrick-rivos commented on test/allowlist/gcc/glibc.log
> +# https://gcc.gnu.org/bugzilla/show_bug.cgi?id=111969
These fails only occur on rv32gcv. We can use a more targeted allowlist file here (we can also just merge a minimal allowlist and have a separate PR to add the flaky fails to that)

2023-11-13 17:48 UTC, merged