add basic nightly runner framework
ewlu/gcc-precommit-ci pull request #937
Opened 2023-12-14 00:33 UTC by ewlu

2023-12-14 19:19 UTC, patrick-rivos requested changes

2023-12-14 19:19 UTC, patrick-rivos commented on .github/workflows/downtime-runner.yaml
> +          TZ=UTC date -d "@$((($(TZ=UTC date -d $END_TIME +%s) + 86399)))" '+%Y-%m-%dT%H:%M:%S' > yesterday_end_date.txt
```suggestion
          # One second less than 24 hrs
          TZ=UTC date -d "@$((($(TZ=UTC date -d $END_TIME +%s) + 86399)))" '+%Y-%m-%dT%H:%M:%S' > yesterday_end_date.txt
```

2023-12-14 19:19 UTC, patrick-rivos commented on .github/workflows/downtime-runner.yaml
> +          python scripts/get_previous_timestamp.py -token ${{ secrets.GITHUB_TOKEN }} -rid ${{ github.run_id }} -repo ewlu/gcc-precommit-ci -workflow Downtime-Runner
This only checks if patchworks is down at this moment? Shouldn't we check if it's been down at any point via artifact shenanigans?

2023-12-14 22:05 UTC, ewlu commented on .github/workflows/downtime-runner.yaml
> +          python scripts/get_previous_timestamp.py -token ${{ secrets.GITHUB_TOKEN }} -rid ${{ github.run_id }} -repo ewlu/gcc-precommit-ci -workflow Downtime-Runner
It's checked 3 steps down. Not sure if that's the best way but open to suggestions

2023-12-20 18:51 UTC, patrick-rivos commented on .github/workflows/downtime-runner.yaml
> +          git submodule update --init riscv-gnu-toolchain
Try deleting this if we only need access to /scripts - if that doesn't work then use the cache for this

2023-12-20 18:51 UTC, patrick-rivos commented on .github/workflows/downtime-runner.yaml
> +          git submodule update --init riscv-gnu-toolchain
Ditto

2023-12-20 18:51 UTC, patrick-rivos commented on .github/workflows/patchworks.yaml
> +          if test -f "./artifact_names.txt"; then
nit: use the bracket notation for test

2023-12-20 19:15 UTC, patrick-rivos approved these changes

2023-12-22 18:26 UTC, merged